name: deploy
on: 
  push: 
    branches: ["main"]

env:
  DOCKER_REPO_URL: ccr.ccs.tencentyun.com
  IMAGE_URL: ${DOCKER_REPO_URL}/macos/web-mac

jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${IMAGE_URL}:${GITHUB_SHA} .
      
      - name: Login Tencent cloud Docker repo
        run: docker login -u ${{secrets.TENCENT_CLOUD_ACCOUNT_ID}} ${DOCKER_REPO_URL}

      - name: Push the Docker image
        run: docker push ${IMAGE_URL}:${GITHUB_SHA}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
      
      - name: Show Docker iamge
        run: docker image ls
